/****** Object:  Table [dbo].[AlbumGenres]    Script Date: 20/03/2020 21:36:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE NAME ='AlbumGenres' AND XTYPE='U')
BEGIN
	CREATE TABLE [dbo].[AlbumGenres](
		[AlbumId] [int] NOT NULL,
		[GenreId] [int] NOT NULL,
	PRIMARY KEY CLUSTERED 
	(
		[AlbumId] ASC,
		[GenreId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]
END
GO