/****** Object:  Table [dbo].[AlbumRecords]    Script Date: 20/03/2020 21:36:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE NAME ='AlbumRecords' AND XTYPE='U')
BEGIN
	CREATE TABLE [dbo].[AlbumRecords](
		[AlbumId] [int] NOT NULL,
		[RecordId] [int] NOT NULL,
	PRIMARY KEY CLUSTERED 
	(
		[AlbumId] ASC,
		[RecordId] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
	) ON [PRIMARY]
END
GO